BeekeepersWeb/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeeKeepersDataBase;
using BeeKeepersBusiness;
using BeekeepersWeb.Models;
using BeeKeepersBusiness.utility;
namespace BeekeepersWeb.Controllers
{

    public class UserProfileController : ApplicationController
    {
        delegate void EmailDelegate(List<UserEmail> lstuseremail);
        public ActionResult Index(Int64 id)
        {
            Int64 actid =0;
            if (Request["actid"] != null)
            {
                actid = Convert.ToInt64(Request["actid"]);
            }
            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"];
                ViewBag.status = TempData["status"];
            }
            ViewBag.type = "current";
            BeeKeepersDataBase.BeeKeepersEntities DB = new BeeKeepersDataBase.BeeKeepersEntities();
            var user = DB.tblusers.Where(s => s.id == id).FirstOrDefault();
            ViewBag.username = user.username;
            ViewBag.userrole = user.usertype;
            ViewBag.activityid = actid;
            ViewBag.userid = user.id;
            ViewBag.activities = ActivityRepository.UserProfileActivities(user.id, DateTime.Now.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), DateTime.Now.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), actid, 5, "", "").ToList();
            return View();
        }
        public ActionResult Search(Int64 id, string latitude, string longitude)
        {
            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"];
                ViewBag.status = TempData["status"];
            }
            ViewBag.type = "current";
            BeeKeepersDataBase.BeeKeepersEntities DB = new BeeKeepersDataBase.BeeKeepersEntities();
            var user = DB.tblusers.Where(s => s.id == id).FirstOrDefault();
            ViewBag.userid = user.id;
            ViewBag.username = user.username;
            ViewBag.userrole = user.usertype;
            ViewBag.userid = user.id;

            ViewBag.activityid = 0;
            ViewBag.latitude = latitude;
            ViewBag.longitude = longitude;
            ViewBag.activities = ActivityRepository.UserProfileActivities(user.id, DateTime.Now.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), DateTime.Now.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), 0, 5, latitude, longitude).ToList();
            return View("index");
        }
        public ActionResult GetActivities(string type, Int64 id,Int64 actid,string latitude, string longitude)
        {
            ViewBag.type = type;
            BeeKeepersDataBase.BeeKeepersEntities DB = new BeeKeepersDataBase.BeeKeepersEntities();
            if (type == "future")
            {
                var user = DB.tblusers.Where(s => s.id == id).FirstOrDefault();
                ViewBag.username = user.username;
                var result = ActivityRepository.UserProfileActivities(id, DateTime.Now.AddDays(1).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), "", actid, 5, latitude, longitude).ToList();
                return PartialView("PVUserProfileActivities", result);
            }
            else if (type == "past")
            {
                var user = DB.tblusers.Where(s => s.id == id).FirstOrDefault();
                ViewBag.username = user.username;
                var result = ActivityRepository.UserProfileActivities(id, "", DateTime.Now.AddDays(-1).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), actid, 5, latitude, longitude).ToList();
                return PartialView("PVUserProfileActivities", result);
            }
            else
            {
                var user = DB.tblusers.Where(s => s.id == id).FirstOrDefault();
                ViewBag.username = user.username;
                var result = ActivityRepository.UserProfileActivities(id, DateTime.Now.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), DateTime.Now.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")), actid, 5, latitude, longitude).ToList();
                return PartialView("PVUserProfileActivities", result);
            }

            //return PartialView("PVUserProfileActivities", null);
        }
        public ActionResult myactivitiesaround(Int64 id)
        {
            ViewBag.acitvityid = id;
            ActivityResponse objactivity = new Activities().EditActivity(id);
            ViewBag.latitude = objactivity.latitude;
            ViewBag.longitude = objactivity.longitude;

            ViewBag.startdate = Convert.ToDateTime(objactivity.startDate).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
            ViewBag.enddate = Convert.ToDateTime(objactivity.endDate).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
            ViewBag.usertype = objactivity.userType;
            var result = ActivityRepository.MyActivitiesAroundList(UserSession.UserId, id, 5);
            return View(result);
        }
        public ActionResult Edit()
        {

            EditProfileModel model = new EditProfileModel();
            BeeKeepersBusiness.User user = new User();
            EditProfile EditProfileResult = user.EditProfile(UserSession.UserId);
            model.lastname = EditProfileResult.lastname;
            model.firstname = EditProfileResult.firstname;
            model.usertype = EditProfileResult.userType;
            model.UserName = EditProfileResult.userName;
            model.Email = EditProfileResult.email;

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProfileModel model)
        {

            BeeKeepersBusiness.User user = new User();
            Int64 status = user.UpdateProfile(UserSession.UserId, UserSession.UserName, "", model.Email, Convert.ToInt32(UserSession.UserRole), model.firstname, model.lastname);
            model.usertype = int.Parse(UserSession.UserRole);
            if (status > 0)
            {
                ViewBag.message = BeeKeepersBusiness.Resource.Profileupdatedsuccessfully;
                ViewBag.status = "1";
            }
            else
            {
                ViewBag.message = BeeKeepersBusiness.Resource.ProfilenotupdatedTryagain;
                ViewBag.status = "0";
            }
            return View(model);

        }
        [HttpPost]
        public ActionResult SendMessage(Int64 id,FormCollection col)
        {
            Int64 actid = 0;
            if (Request["actid"] != null)
            {
                actid = Convert.ToInt64(Request["actid"]);
            }
            using (Messages messages = new Messages())
            {
                if (id != null)
                {
                    Int64? result = messages.SendMessage(UserSession.UserId, id, col["txtMessage"].ToString(), "",1);
                    if (result != null && result > 0)
                    {
                        var installation = Data.Entities.tblinstallations.Where(s => s.userid == id).ToList();
                        var fromuserinfo = Data.Entities.tblusers.Where(s => s.id == UserSession.UserId).FirstOrDefault();
                        var touserinfo = Data.Entities.tblusers.Where(s => s.id == id).FirstOrDefault();

                        string langEmail = new Common().GetLanguage4Emails(id);
                        List<UserEmail> lstuseremail = new List<UserEmail>();
                        UserEmail objuseremail = new UserEmail();
                        objuseremail.fromUserName = fromuserinfo.username;
                        objuseremail.toUserName = touserinfo.username;
                        objuseremail.toEmailId = touserinfo.email;
                        objuseremail.UserLanguage = langEmail;
                        objuseremail.message = fromuserinfo.username + " " + new SiteLanguages().GetResxNameByValue(langEmail, "sentyouamessage");
                        lstuseremail.Add(objuseremail);

                        int? badgecount = new Common().GetNotificationCounter(id);
                        if (installation != null)
                        {
                            foreach (var item in installation)
                            {
                                string langnoti = new Common().GetLanguage4Notification(item.userid);
                                if (item.devicetype == "1")
                                {
                                    iPhonePush.SendNotice(item.devicetoken, fromuserinfo.username + " " + new SiteLanguages().GetResxNameByValue(langnoti, "sentyouamessage"), badgecount, "Message", UserSession.UserId, result, "");
                                }
                                else if (item.devicetype == "2")
                                {
                                    AndroidPushNotice.SendNotice(item.devicetoken, fromuserinfo.username + " " + new SiteLanguages().GetResxNameByValue(langnoti, "sentyouamessage"), badgecount, "Message", UserSession.UserId,result, "");
                                }
                            }
                            EmailDelegate emailDelegate = new EmailDelegate(UserEmail.SendNotificationMails4Message);
                            AsyncCallback cb = new AsyncCallback(MyAsyncCallback);
                            IAsyncResult ar = emailDelegate.BeginInvoke(lstuseremail, cb, emailDelegate);

                        }
                        TempData["message"] = Resource.Messagesentto + " " + objuseremail.toUserName;
                        TempData["status"] = "1";
                    }
                    else
                    {
                        TempData["message"] = Resource.Messagenotsent;
                        TempData["status"] = "0";
                    }
                }

BeekeepersWeb/Views/UserProfile/Edit.cshtml
@model BeekeepersWeb.Models.EditProfileModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    
    $(document).ready(function () {
        $("#editprofile").addClass("leftmenuactive");
    });
    //function ResetForm() {
    //    $("#firstname").val("");
    //    $("#lastname").val("");
      
    //    $("#Pasword").val("");
    //    $("#ConfirmPasword").val("");
    //    $("#Email").val("");

    //}
</script>
<style type="text/css">
    .form_left {
        float: left;
        margin: 0px 5px 5px 145px;
        width: 60%;
    }
</style>
@Html.Partial("loginmenus")
@using (Html.BeginForm())
{
    

    <div class="right-db">
        <div class="full">
            <h1><i>
                <img src="~/images/member_login.png"></i>@BeeKeepersBusiness.Resource.UpdateProfile
            </h1>
        </div>
        @Html.Partial("ValidationSummary", ViewData.ModelState)
        <div id="message">

            @if (@ViewBag.status != null && @ViewBag.status == "1")
            {
                <div class="alert alert-success" role="alert">@ViewBag.message</div> 
                <script type="text/javascript">
                    window.setTimeout(function () { HideMessage(); }, 2000);
                </script>
            }
            else if (@ViewBag.status != null && @ViewBag.status == "0")
            { 
                <div class="alert alert-danger" role="alert">@ViewBag.message</div>   
                <script type="text/javascript">
                    window.setTimeout(function () { HideMessage(); }, 2000);
                </script>
            }
        </div>
        <div class="clear"></div>
        <div class="Register_bg">

            <div class="form_left">
                @Html.TextBoxFor(model => model.firstname, new { @placeholder = @BeeKeepersBusiness.Resource.Firstnamewillbekeptprivate, maxlength = 100, autocomplete = "off" })
            </div>
            <div class="form_left">
                @Html.TextBoxFor(model => model.lastname, new { @placeholder = @BeeKeepersBusiness.Resource.Lastnamewillbekeptprivate, maxlength = 100, autocomplete = "off" })

            </div>
            <div class="form_left">
                @Html.TextBoxFor(model => model.UserName, new { @readonly = "true", maxlength = 100, autocomplete = "off" })
            </div>
            <div class="form_left">
                @Html.TextBoxFor(model => model.Email, new { @placeholder = @BeeKeepersBusiness.Resource.Emailwillbekeptprivate, maxlength = 100, autocomplete = "off" })
            </div>
            <div class="clear"></div>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @BeeKeepersBusiness.Resource.Iama
            <center>
             <div style="margin-left:-50px;"> 
                <table width="50%">
                    <tr>
                        <td align="center">  <img src="~/Images/farmer.png" alt="@BeeKeepersBusiness.Resource.Farmer" title="@BeeKeepersBusiness.Resource.Farmer"  /></td>
                        <td align="center"><img src="~/Images/tractor.png" alt="@BeeKeepersBusiness.Resource.Contractor" title="@BeeKeepersBusiness.Resource.Contractor" /></td>
                        <td align="center">  <img src="~/Images/bee.png" alt="@BeeKeepersBusiness.Resource.Beekeeper" title="@BeeKeepersBusiness.Resource.Beekeeper" /></td>
                    </tr>
                      <tr>
                        <td align="center"> @Html.RadioButtonFor(Model => Model.usertype, 2, new { @id = "usertype2", @disabled = "disabled" })</td>
                        <td align="center"> @Html.RadioButtonFor(Model => Model.usertype, 3, new { @id = "usertype3", @disabled = "disabled" })</td>
                        <td align="center"> @Html.RadioButtonFor(Model => Model.usertype, 1, new { @id = "usertype1", @disabled = "disabled" })</td>
                    </tr>
                </table>
              </div>
            </center>
        </div>
        <div class="Register_bottom">
            @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value=="fr")
            {
                <input type="image" src="~/Images/submit_BTN.png" />
                <a href="@Url.Action("index","dashboard")"><img style="cursor: pointer;" src="~/images/cancel_btn.png"></a>
            }
            else
            {
                <input type="image" src="~/Images/submit_BTN_en.png" />
                <a href="@Url.Action("index","dashboard")"><img style="cursor: pointer;" src="~/images/cancel_btn_en.png"></a>
            }
            
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeekeepersWeb/Views/UserProfile/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .anchor_view {
    color: #0b4b00;
    padding: 3px;
    text-decoration: none;
    }
    .anchor_view:hover {
        background: none repeat scroll 0 0 #fff;
    border-radius: 5px;
    color: #0b4b00;
    padding: 3px;
    text-decoration: none;
    }
    .current_active {
        background: url('@(System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString())/images/current_check_@(Request.Cookies.Get("culture").Value).png') repeat scroll 0 0 rgba(0, 0, 0, 0);
        float: left;
        height: 56px;
        width: 51px;
        margin-left: 125px;
    }
    .current {
        background: url('@(System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString())/Images/current_uncheck_@(Request.Cookies.Get("culture").Value).png') repeat scroll 0 0 rgba(0, 0, 0, 0);
        float: left;
        height: 56px;
        width: 51px;
        margin-left: 125px;
    }

    .past {
        background: url('@(System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString())/Images/past_uncheck_@(Request.Cookies.Get("culture").Value).png');
        float: left;
        height: 56px;
        width: 51px;
        margin-left: 125px;
    }
    .past_active {
        background: url('@(System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString())/Images/past_check_@(Request.Cookies.Get("culture").Value).png');
        float: left;
        height: 56px;
        width: 51px;
        margin-left: 125px;
    }
    .future_active {
        background: url('@(System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString())/Images/future_check_@(Request.Cookies.Get("culture").Value).png');
        float: left;
        height: 56px;
        width: 51px;
        margin-left: 125px;
    }
    .future {
        background: url('@(System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString())/Images/future_uncheck_@(Request.Cookies.Get("culture").Value).png');
        float: left;
        height: 56px;
        width: 51px;
        margin-left: 125px;
    }
</style>
<script type="text/javascript">
    function ShowBroadcast() {
        $("#div_broadcast").slideDown(500);
    }
    function HideBroadcast() {
        document.getElementById("txtmessage").value = "";
        $("#div_broadcast").slideUp(500);
    }
    function messagevalidation() {
        if (document.getElementById("txtmessage").value == "") {
            alert("@BeeKeepersBusiness.Resource.Pleaseentermessage");
                    return false;
                }
                else {
                    return true;
                }
            }
</script>
@Html.Partial("loginmenus")
<div class="right-db">
    <div class="full">
        <h1>User Profile</h1>
    </div>
    <div style="float: left; padding: 10px; text-align: justify">
        <div style="float: left; margin-bottom: 15px; background: none repeat scroll 0% 0% rgb(217, 234, 210); padding: 9px; width: 660px;">
            <div style="float: left; width: 100px;">
                @if (@ViewBag.userrole == 1)
                {
                    <img src="~/Images/bee.png" /> 
                }
                else if (@ViewBag.userrole == 1)
                {
                    <img src="~/Images/farmer.png" />
                }
                else
                {
                    <img src="~/Images/tractor.png" />
                }


                
            </div>
            <div style="float: left; text-align: center; width: 437px; font-weight: bold; color: rgb(11, 75, 0);">
                @ViewBag.username @BeeKeepersBusiness.Resource.Activities
            </div>
            <div style="float: right; width: 24px;">
                @*<a href="@Url.Action("index", "usermessage")">*@
                    <img src="~/Images/emailicon@2x.png" style="cursor: pointer;" title="@BeeKeepersBusiness.Resource.SendMessage" onclick="ShowBroadcast();" />@*</a>*@
            </div>
        </div>
        <div id="message">
            @if (@ViewBag.status != null && @ViewBag.status == "1")
            {
            
                <div class="alert alert-success" role="alert">@ViewBag.message</div> 
                <script type="text/javascript">
                    $(document).ready(function () {
                        document.getElementById("txtmessage").value = "";
                    });
                    window.setTimeout(function () { HideMessage(); }, 2000);
                </script>
            }
            else if (@ViewBag.status != null && @ViewBag.status == "0")
            { 
                <div class="alert alert-danger" role="alert">@ViewBag.message</div>   
                <script type="text/javascript">
                    $(document).ready(function () {

                        $("#div_broadcast").slideDown(500);
                    });
                    window.setTimeout(function () { HideMessage(); }, 2000);
                </script>
            }
        </div>
        <div style=" background: none repeat scroll 0 0 rgb(255, 255, 255);border: 2px solid #0b4b00;float: left;height: 105px;position: absolute;top: auto;width: 675px;z-index: 10000;margin-top:45px; display: none;" id="div_broadcast">
                    @using (Html.BeginForm("SendMessage", "UserProfile", new { id = ViewBag.userid, actid = @ViewBag.activityid }, FormMethod.Post))
                    {
                        @Html.TextArea("txtmessage", new { @class = "broadcasttextarea1", @placeholder = @BeeKeepersBusiness.Resource.Message })
                        <div class="input_block">
                            
                            <div style="float: right; width: 84px;">
                                @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value=="fr")
                                {
                                    <img   style="height:28px;cursor:pointer;" src="~/Images/cancelbtn1.png" onclick="HideBroadcast();" />
                                }
                                else
                                {
                                    <img   style="height:28px;cursor:pointer;" src="~/Images/cancelbtn1_en.png" onclick="HideBroadcast();" />
                                }
                            </div>
                            <div style="float: right; width: 71px;">
                                @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value=="fr")
                                {
                                    <input type="image" src="~/Images/send_BTN.png" style="width: 65px; height: 28px; float: left" onclick="return messagevalidation();" />
                                }
                                else
                                {
                                    <input type="image" src="~/Images/send_BTN_en.png" style="width: 65px; height: 28px; float: left" onclick="return messagevalidation();" />
                                }

                            </div>
                        </div>
                    }

                </div>
        <div style="float: left; width: 680px;">
            <div style="float: left; text-align: center; width: 220px;">
                @Ajax.ActionLink(" ", "GetActivities", "userprofile", new { id = @ViewBag.userid, type = "current",actid=@ViewBag.activityid,@latitude=@ViewBag.latitude,@longitude=@ViewBag.longitude }, new AjaxOptions { UpdateTargetId = "div_activities" }, new { @class = "current_active", @id = "current" })
            </div>
            <div style="float: left; text-align: center; width: 220px;">
                @Ajax.ActionLink(" ", "GetActivities", "userprofile", new { id = @ViewBag.userid, type = "future",actid=@ViewBag.activityid,@latitude=@ViewBag.latitude,@longitude=@ViewBag.longitude }, new AjaxOptions { UpdateTargetId = "div_activities" }, new { @class = "future", @id = "future" })
            </div>
            <div style="float: left; text-align: center; width: 220px;">
                @Ajax.ActionLink(" ", "GetActivities", "userprofile", new { id = @ViewBag.userid, type = "past",actid=@ViewBag.activityid,@latitude=@ViewBag.latitude,@longitude=@ViewBag.longitude }, new AjaxOptions { UpdateTargetId = "div_activities" }, new { @class = "past", @id = "past" })
            </div>
        </div>
        <div style="float: left; width: 680px;">
            <div id="div_activities" style=" float: left;height: 477px !important;margin-top: 10px;overflow-y: auto;width: 699px;">
                @if (@ViewBag.activities != null && (@ViewBag.activities as ICollection<BeeKeepersDataBase.sp_Userprofileactivities_Result>).Count() > 0)
                {
                    foreach (var item in @ViewBag.activities)
                    {
                    <div style="float: left; border-bottom: 1px solid; padding: 10px; background: none repeat scroll 0% 0% rgb(219, 219, 219); width: 660px;">
                        <div style="float: left; height: 20px; width: 650px;">
                            <img src="~/Images/calendar_icon@2X.png" style="margin-right: 10px; float: left;" /><div style="float: left;font-size:13px;">@Convert.ToDateTime(@item.startdate).ToString("dd-MMM-yyyy",new System.Globalization.CultureInfo("en-US")) - @Convert.ToDateTime(@item.enddate).ToString("dd-MMM-yyyy",new System.Globalization.CultureInfo("en-US"))</div>
                            <div style="float: left; width: 250px; margin-left: 40px;">
                                <a class="anchor_view" href="@Url.Action("myactivitiesaround", "userprofile", new { @id = @item.id })">
                                <img src="~/Images/editgreen_icon.png" />
                                &nbsp;@BeeKeepersBusiness.Resource.Viewnearbyactivities</a></div>
                        </div>
                        <div style="float: left; padding: 10px; width: 650px;">
                            @item.note
                        </div>
                    </div>
                        
                    }
                }
                else
                {
                    <div style="float: left; padding: 10px; width: 650px;text-align:center;">@BeeKeepersBusiness.Resource.Activitiesnotexist</div>
                }

                
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
    $('#current').click(function () {
        $('#div_activities').html('<div style="margin: 100px auto; width: 150px; white-space: nowrap; height: 112px;text-align: center; z-index: 1000;"><table border="0" style="text-align: center;"><tr><td align="left"><img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"]/Images/loading.gif" /></td></tr></table></div>');
    });
    $('#future').click(function () {
        $('#div_activities').html('<div style="margin: 100px auto; width: 150px; white-space: nowrap; height: 112px;text-align: center; z-index: 1000;"><table border="0" style="text-align: center;"><tr><td align="left"><img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"]/Images/loading.gif" /></td></tr></table></div>');
    });
    $('#past').click(function () {
        $('#div_activities').html('<div style="margin: 100px auto; width: 150px; white-space: nowrap; height: 112px;text-align: center; z-index: 1000;"><table border="0" style="text-align: center;"><tr><td align="left"><img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"]/Images/loading.gif" /></td></tr></table></div>');
    });
</script>

BeekeepersWeb/Views/UserProfile/PVUserProfileActivities.cshtml
@model IEnumerable<BeeKeepersDataBase.sp_Userprofileactivities_Result>
<script type="text/javascript">
    @if (ViewBag.type == "current")
    { 
        @:document.getElementById("current").className = "current_active";
        @:document.getElementById("past").className= "past";
        @:document.getElementById("future").className = "future";
    }
    else if (ViewBag.type == "past")
    {
        @:document.getElementById("current").className = "current";
        @:document.getElementById("past").className = "past_active";
        @:document.getElementById("future").className = "future";
    }
    else
    {
        @:document.getElementById("current").className = "current";
        @:document.getElementById("past").className = "past";
        @:document.getElementById("future").className = "future_active";
        
    }
</script>
@if (Model != null && Model.Count()>0)
{
    foreach (var item in Model)
    {
        <div style="float: left; border-bottom: 1px solid; padding: 10px; background: none repeat scroll 0% 0% rgb(219, 219, 219); width: 660px;">
            <div style="float: left; height: 20px; width: 650px;">
                <img src="~/Images/calendar_icon@2X.png" style="margin-right:10px;float:left;" /><div style="float:left;font-size:13px;">@Convert.ToDateTime(@item.startdate).ToString("dd-MMM-yyyy",new System.Globalization.CultureInfo("en-US")) - @Convert.ToDateTime(@item.enddate).ToString("dd-MMM-yyyy",new System.Globalization.CultureInfo("en-US"))</div>
                <div style="float:left;width:200px;margin-left:40px;">
                    <a href="@Url.Action("myactivitiesaround", "userprofile", new { @id = @item.id })" style="font-size:13px;text-decoration:none;color:#000;"><img src="~/Images/editgreen_icon.png" /> 
                        &nbsp;@BeeKeepersBusiness.Resource.Viewnearbyactivities</a></div>
            </div>
            <div style="float: left; padding: 10px; width: 650px;">
                @item.note
            </div>
        </div>
                        
    }
}
else
{
    <div style="float: left; padding: 10px; width: 650px;text-align:center;">@BeeKeepersBusiness.Resource.Activitiesnotexist</div>
}