BeekeepersWeb/Controllers/ContactusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeekeepersWeb.Controllers
{
    public class ContactusController : MyBaseController
    {
        //
        // GET: /Contactus/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Models.ContactusModel model)
        {
            BeeKeepersBusiness.User user = new BeeKeepersBusiness.User();

            string email = model.email;
            string contactno = model.contactno;
            string query = model.query;
            string name = model.name;
            int status = user.SendConatctusmail(name, email, contactno, query);
            if (status == 1)
            {
                ViewBag.message = BeeKeepersBusiness.Resource.YourquerysenttoBeeconnectedAdmin;
                ViewBag.status = "1";
            }
            else
            {
                ViewBag.message = BeeKeepersBusiness.Resource.Unabletoprocess;
                ViewBag.status = "0";
            }
            ModelState.Clear();
            return View();

        }

    }
}

BeekeepersWeb/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BeekeepersWeb.Controllers
{
    public class DashboardController : ApplicationController
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

BeekeepersWeb/Controllers/NearbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeeKeepersBusiness;
using BeeKeepersDataBase;
using GoogleMaps.LocationServices;

namespace BeekeepersWeb.Controllers
{
    public class NearbyController : ApplicationController
    {
        //
        // GET: /Nearby/

        public ActionResult Index()
        {
            ViewBag.lstactivity = new BeeKeepersBusiness.Activities().GetUserActivityList(UserSession.UserId).OrderByDescending(s => s.startdate).ToList();
            ViewBag.lstproperty = new BeeKeepersBusiness.Property().PropertyList(UserSession.UserId).OrderBy(s => s.propertyName).ToList();
            return View();
        }

        public PartialViewResult ActivityList(Int64 id, string startdate, string enddate)
        {
            if (startdate != null && startdate != "")
            {
                startdate = DateTime.ParseExact(startdate, "dd-MM-yyyy", null).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
            }
            if (enddate != null && enddate != "")
            {
                enddate = DateTime.ParseExact(enddate, "dd-MM-yyyy", null).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
            }
            ActivityResponse result = new Activities().EditActivity(id);
            ViewBag.latitude = result.latitude;
            ViewBag.longitude = result.longitude;
            ViewBag.actid = id;
            List<sp_ListActivities_Result> aroundactivity = ActivityRepository.ActivityList(UserSession.UserId, Convert.ToInt64(UserSession.UserRole), result.latitude, result.longitude, startdate, enddate, 5);
            int count = aroundactivity.Count;
            if (UserSession.UserRole == "1")
            {
                var Propertyresult = BeeKeepersDataBase.PropertyRepository.NearestProperty(5, result.latitude, result.longitude);
                foreach (var item in Propertyresult)
                {
                    count = count + 1;
                    //MyActivitiesAroundResponse n =new MyActivitiesAroundResponse();

                    sp_ListActivities_Result n = new sp_ListActivities_Result();
                    n.latitude = item.latitude;
                    n.longitude = item.longitude;
                    n.usertype = 2;
                    n.note = item.propertyname;
                    n.username = item.username;
                    n.userid = item.userid;
                    aroundactivity.Add(n);
                }
            }

            return PartialView(aroundactivity);
        }

        public PartialViewResult PropertyList(Int64 id, string startdate, string enddate)
        {
            PropertyResponse propertiesresult = new Property().EditProperty(id);
            ViewBag.Platitude = propertiesresult.latitude;
            ViewBag.Plongitude = propertiesresult.longitude;
            ViewBag.pid = id;
            if (startdate != null && startdate != "")
            {
                startdate = DateTime.ParseExact(startdate, "dd-MM-yyyy", null).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
            }
            if (enddate != null && enddate != "")
            {
                enddate = DateTime.ParseExact(enddate, "dd-MM-yyyy", null).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
            }
            List<sp_ListActivities_Result> lstPropertyresult = ActivityRepository.ActivityList(UserSession.UserId, Convert.ToInt64(UserSession.UserRole), propertiesresult.latitude, propertiesresult.longitude, startdate, enddate, 5);

            return PartialView(lstPropertyresult);
        }


        public PartialViewResult Search(string startdate, string enddate, string searchtext)
        {
            AddressData addresses = new AddressData();
            addresses.Address = searchtext;
            addresses.Zip = null;
            var gls = new GoogleLocationService();
            try
            {
                var latlong = gls.GetLatLongFromAddress(addresses);
                string Latitude = Convert.ToString(latlong.Latitude).Replace(",",".");
                string Longitude = Convert.ToString(latlong.Longitude).Replace(",", "."); ;

                ViewBag.Platitude = Latitude;
                ViewBag.Plongitude = Longitude;
                if (startdate != null && startdate != "")
                {
                    startdate = DateTime.ParseExact(startdate, "dd-MM-yyyy", null).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
                }
                if (enddate != null && enddate != "")
                {
                    enddate = DateTime.ParseExact(enddate, "dd-MM-yyyy", null).ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"));
                }
                var id = UserSession.UserId;
                var name = UserSession.UserName;
                var role = UserSession.UserRole;
                List<sp_ListActivities_Result> lstPropertyresult = ActivityRepository.ActivityList(UserSession.UserId, Convert.ToInt64(UserSession.UserRole), Latitude, Longitude, startdate, enddate, 5);
                return PartialView(lstPropertyresult);
            }
            catch (Exception ex)
            {
                return PartialView("defaultmap");
            }
            
        }


    }
}

BeekeepersWeb/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeeKeepersBusiness;
using BeeKeepersDataBase;
using PagedList;

namespace BeekeepersWeb.Controllers
{
    public class PropertyController : ApplicationController
    {
        public ActionResult Index(int? page)
        {
            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"];
                ViewBag.status = TempData["status"];
            }
            var result = new Property().PropertyList_front(UserSession.UserId).ToList();
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(result.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BeekeepersWeb.Models.PropertyModel Model)
        {
            try
            {
                Property property = new Property();
                Int64? result = property.AddProperty(UserSession.UserId, Model.latitude, Model.longitude, Model.PropertyName);
                if (result != null && result > 0)
                {
                    ModelState.Clear();
                    TempData["message"] = BeeKeepersBusiness.Resource.Propertyaddedsuccessfully;
                    TempData["status"] = "1";
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("", BeeKeepersBusiness.Resource.PropertynotaddedTryagain);

                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", BeeKeepersBusiness.Resource.PropertynotaddedTryagain);
                return View();
            }
            
        }

        public ActionResult Edit(int id)
        {
            try
            {
                if (TempData["message"] != null)
                {
                    ViewBag.message = TempData["message"];
                    ViewBag.status = TempData["status"];
                }
                PropertyResponse EditProperty = new Property().EditProperty(id);
                if (EditProperty != null)
                {
                    BeekeepersWeb.Models.PropertyModel model = new Models.PropertyModel();
                    model.PropertyName = EditProperty.propertyName;
                    model.latitude = EditProperty.latitude;
                    model.longitude = EditProperty.longitude;
                    return View(model);
                }
                else
                {
                    TempData["message"] =BeeKeepersBusiness.Resource.Propertydetailsnotget;
                    TempData["status"] = "0";
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                TempData["message"] = BeeKeepersBusiness.Resource.Propertydetailsnotget;
                TempData["status"] = "0";
                return RedirectToAction("index");
            }
            

        }
        public ActionResult Cancel()
        {
            return RedirectToAction("index");
        }
        [HttpPost]
        public ActionResult Edit(BeekeepersWeb.Models.PropertyModel model)
        {
            try
            {
                Int64? status = new Property().UpdateProperty(UserSession.UserId, model.latitude, model.longitude, model.PropertyName, Convert.ToInt64(model.id));
                if (status != null && status > 0)
                {
                    TempData["message"] = BeeKeepersBusiness.Resource.Propertyupdatedsuccessfully;
                    TempData["status"] = "1";
                    return RedirectToAction("index");
                }
                else
                {
                    TempData["message"] =BeeKeepersBusiness.Resource.PropertynotupdatedTryagain;
                    TempData["status"] = "0";
                }
                return RedirectToAction("Edit", model.id);
            }
            catch (Exception ex)
            {
                TempData["message"] = BeeKeepersBusiness.Resource.PropertynotupdatedTryagain;
                TempData["status"] = "0";
                return RedirectToAction("Edit", model.id);
            }
        }

        public ActionResult Delete(int id)
        {
            Int64? result = new Property().DeleteProperty(id);
            if (result != null && result == 1)
            {
                TempData["message"] =BeeKeepersBusiness.Resource.Propertydeletedsuccessfully;
                TempData["status"] = "1";

            }
            else
            {
                TempData["message"] = BeeKeepersBusiness.Resource.PropertynotdeletedTryagain;
                TempData["status"] = "0";
            }
            return RedirectToAction("index");
        }
        public ActionResult ViewAround(Int64 id)
        {
            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"];
                ViewBag.status = TempData["status"];
            }
            if (TempData["txtmessage"] != null)
            {
                ViewBag.txtmessage = TempData["txtmessage"];
            }
            PropertyResponse objproperty = new Property().EditProperty(id);
            ViewBag.userid = objproperty.userId;
            ViewBag.Propertyid = objproperty.propertyId;
            ViewBag.propertyName = objproperty.propertyName;
            ViewBag.latitude = objproperty.latitude;
            ViewBag.longitude = objproperty.longitude;
            Activities activities = new Activities();
            string startdate = string.Format("{0:dd/MM/yyyy}", DateTime.Now.ToString("dd/MM/yyyy"));
            var activityArround = activities.ActivityList4Web(UserSession.UserId, Convert.ToInt64(UserSession.UserRole), objproperty.latitude, objproperty.longitude, startdate, "", 5);
            return View(activityArround);
        }
        
    }
}

BeekeepersWeb/Views/Shared/Loginmenus.cshtml
@if (BeekeepersWeb.UserSession.UserId != null && BeekeepersWeb.UserSession.UserId.ToString() != "0")
{ 
    <div class="left-menu">
    <ul class="lt-nav">
        @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "fr")
        {
            <li><a id="dashboard1" href="@Url.Action("index", "Dashboard")" class="first"><img src="~/images/icon-dashboard.png" @*alt="Dashboard"*@ class="md-align" />&nbsp;&nbsp;Tableau de bord</a></li>
            <li><a id="editprofile" href="@Url.Action("Edit", "UserProfile")"><img src="~/images/icon-edit-profile.png" @*alt="Edit Profile"*@ class="md-align" />&nbsp;&nbsp;Modifier le profil</a></li>
            if (BeekeepersWeb.UserSession.UserRole != null && BeekeepersWeb.UserSession.UserRole.ToString() == "2")
            {
                <li><a id="property" href="@Url.Action("index", "Property")"><img src="~/images/icon-property.png" @*alt="My Property"*@ class="md-align" />&nbsp;&nbsp;Ma propriété</a></li>
            }
            if (BeekeepersWeb.UserSession.UserRole != null && BeekeepersWeb.UserSession.UserRole.ToString() == "1")
            {
                <li><a id="myactivities" href="@Url.Action("index", "UserActivity")"><img src="~/images/bee.png" @*alt="My Activities"*@ class="md-align" />&nbsp;&nbsp;Mes activités</a></li>
            }
            else
            { 
                <li><a id="myactivities" href="@Url.Action("index", "UserActivity")"><img src="~/images/icon-my-activities.png" @*alt="My Activities"*@ class="md-align" />&nbsp;&nbsp;Mes activités</a></li>
            }
            <li><a id="nearby" href="@Url.Action("index", "Nearby")"><img src="~/images/icon-nearby.png" @*alt="Nearby"*@ class="md-align" />&nbsp;&nbsp;À proximité</a></li>
            <li><a id="messages" href="@Url.Action("index", "UserMessage")"><img src="~/images/icon-messages.png" @*alt="Messages"*@ class="md-align" />&nbsp;&nbsp;Mes messages</a></li>
            <li><a id="createactivity" href="@Url.Action("Create", "UserActivity")"><img src="~/images/icon-dashboard.png" @*alt="Add New Activity"*@ class="md-align" />&nbsp;&nbsp;Ajouter une nouvelle activité</a></li>
            <li><a id="changepassword" href="@Url.Action("ChangePassword", "UserLogin")" class="last"><img src="~/images/icon-edit-profile.png" @*alt="Edit Profile"*@ class="md-align" />&nbsp;&nbsp;Changer mot de passe</a></li>
        }
        else
        {
            <li><a id="dashboard1" href="@Url.Action("index", "Dashboard")" class="first"><img src="~/images/icon-dashboard.png" @*alt="Dashboard"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.Dashboard</a></li>
            <li><a id="editprofile" href="@Url.Action("Edit", "UserProfile")"><img src="~/images/icon-edit-profile.png" @*alt="Edit Profile"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.EditProfile</a></li>
            if (BeekeepersWeb.UserSession.UserRole != null && BeekeepersWeb.UserSession.UserRole.ToString() == "2")
            {
                <li><a id="property" href="@Url.Action("index", "Property")"><img src="~/images/icon-property.png" @*alt="My Property"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.MyProperty</a></li>
            }
            if (BeekeepersWeb.UserSession.UserRole != null && BeekeepersWeb.UserSession.UserRole.ToString() == "1")
            {
                <li><a id="myactivities" href="@Url.Action("index", "UserActivity")"><img src="~/images/bee.png" @*alt="My Activities"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.MyActivities</a></li>
            }
            else
            { 
                <li><a id="myactivities" href="@Url.Action("index", "UserActivity")"><img src="~/images/icon-my-activities.png" @*alt="My Activities"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.MyActivities</a></li>
            }
            <li><a id="nearby" href="@Url.Action("index", "Nearby")"><img src="~/images/icon-nearby.png" @*alt="Nearby"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.Nearby</a></li>
            <li><a id="messages" href="@Url.Action("index", "UserMessage")"><img src="~/images/icon-messages.png" @*alt="Messages"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.Messages</a></li>
            <li><a id="createactivity" href="@Url.Action("Create", "UserActivity")"><img src="~/images/icon-dashboard.png" @*alt="Add New Activity"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.AddNewActivity</a></li>
            <li><a id="changepassword" href="@Url.Action("ChangePassword", "UserLogin")" class="last"><img src="~/images/icon-edit-profile.png" @*alt="Edit Profile"*@ class="md-align" />&nbsp;&nbsp;@BeeKeepersBusiness.Resource.ChangePassword
</a></li>
        }
    </ul>
</div>
}

BeekeepersWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>BeeConnected</title>

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @*<script type="text/javascript">
        window.location = "index.html";
    </script>*@


    <style type="text/css">
           a {
            outline:0 !important;
        }
       
        .alert-danger {
            background-color: #f2dede;
            border-color: #ebccd1;
            color: #a94442;
            float: left;
            margin-left: 20px;
            margin-top: 10px;
            padding: 10px;
            width: 91%;
        }

        .field-validation-valid {
            padding: 10px;
        }

        .loginmenu1 {
            font-size: 13px;
            font-weight: bold;
            float: left;
            height: 25px;
            width: 143px;
            padding: 5px;
            background: #DDE6C3;
            color: #18723D;
        }

        .loginmenu2 {
            font-size: 13px;
            font-weight: bold;
            float: left;
            height: 25px;
            width: 143px;
            padding: 5px;
            background: #F4F2D1;
            color: #18723D;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.10.2/jquery-ui.min.js" integrity="sha256-FgiaQnQazF/QCrF9qSvpRY6PACn9ZF8VnlgqfqD1LsE=" crossorigin="anonymous"></script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/style.css" rel="stylesheet" />
    <script type="text/javascript">
        function HideMessage() {
            window.setTimeout(function () { $('#message').fadeOut(1000); }, 2000);
        }

        // https://weblog.west-wind.com/posts/2014/Mar/27/Auto-Selecting-Cultures-for-Localization-in-ASPNET
        // System culture curently set to: @System.Threading.Thread.CurrentThread.CurrentUICulture.ToString();
        @if (Request.Cookies.Get("culture") == null)
        {
            @Html.Raw("// Request culture curently null");
            if (HttpContext.Current != null && HttpContext.Current.Request.UserLanguages != null)
            {
                if (Request.UserLanguages.Length > 0) {
                    if(Request.UserLanguages[0].ToLower().StartsWith("fr")) {
                        if (System.Threading.Thread.CurrentThread.CurrentUICulture.ToString() != "fr") {
                            @Html.Raw("\ndocument.location = '/Home/ChangeLanguage?lang=fr';\n");
                        }
                    }
                }
            }
        } else {
            @Html.Raw("// Request culture curently set to: ")
            @Request.Cookies.Get("culture").Value
        }


    </script>
    <script src="~/Scripts/nicescroll.js"></script>
</head>
<body>
    <div id="main-wrapper">
        <div id="wrapper">
            <div id="header">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")" title="BeeConnected">
                        <img style="width:193px; height:auto;" src="~/images/beeconnected_logo.png" alt="BeeConnected" style="border:none;" />
                    </a>
                </div>
                <div>

                <ul class="nav">
                    <li><a href="@Url.Action("index", "Home")" id="Home" title="@BeeKeepersBusiness.Resource.Home">@BeeKeepersBusiness.Resource.Home</a></li>
                    <li><a href="@Url.Action("aboutus", "page")" id="aboutus" title="@BeeKeepersBusiness.Resource.Aboutus">@BeeKeepersBusiness.Resource.Aboutus</a></li>
                    <li><a href="@Url.Action("resource", "page")" id="resource" title="@BeeKeepersBusiness.Resource.Resources">@BeeKeepersBusiness.Resource.Resources</a></li>
                    <li><a href="@Url.Action("index", "Contactus")" id="Contactus" title="@BeeKeepersBusiness.Resource.Contactus"><span>@BeeKeepersBusiness.Resource.Contactus</span></a></li>
                    @if (BeekeepersWeb.UserSession.UserId != null && BeekeepersWeb.UserSession.UserId.ToString() != "0")
                    { 
                        <li><a href="@Url.Action("index", "dashboard")" id="dashboard" title="@BeeKeepersBusiness.Resource.Dashboard">@BeeKeepersBusiness.Resource.Dashboard</a></li>
                    }
                    @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "fr")
                    {
                        <li><a href="@Url.Action("ChangeLanguage", "Home", new { lang = "en" })" title="Click to view English website">English</a></li>
                    }
                    else 
                    {
                        <li><a href="@Url.Action("ChangeLanguage", "Home", new { lang = "fr" })" title="Click to view Francais website">Francais</a></li>
                    }
                </ul>
                
                </div>

            </div>
            <div id="container">

                <div class="left-sec">

                    <div class="full">

                        <div class="registersec shade1">
                            <div style="float: left; margin-right: 10px; margin-top: 5px;">
                                <img src="~/Images/login_icon.png" />
                            </div>
                            <div style="float: left;">
                                @if (Session["userid"] != null && Session["UserName"] != null && Session["userid"].ToString() != "")
                                {
                                    @Session["UserName"].ToString() <a href="@Url.Action("logout", "userlogin")" title="@BeeKeepersBusiness.Resource.Logout" style="margin-left: 11px; font-weight: bold;">@BeeKeepersBusiness.Resource.Logout</a>
                                }
                                else
                                {
                                    <a href="@Url.Action("login", "userlogin")" title="@BeeKeepersBusiness.Resource.Login">@BeeKeepersBusiness.Resource.Login</a> <span>&#47;</span> <a href="@Url.Action("create", "registration")" title="@BeeKeepersBusiness.Resource.Register">@BeeKeepersBusiness.Resource.Register</a>                                                                      
                                }
                            </div>

                        </div>
                    </div>

                    <div class="full">

                        @RenderBody()
                    </div>


                </div>
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="main-footer">
            <div class="upper-footer">
                <div class="left-footer">
                    @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "fr")
                    {
                        <a href="http://www.croplife.ca/fr" target="_blank">
                            <img style="width:250px; height:auto;" src="~/images/footer-logo.png" alt="BeeConnected" />
                        </a>
                    }
                    else
                    {
                        <a href="http://www.croplife.ca" target="_blank">
                            <img style="width:250px; height:auto;" src="~/images/footer-logo.png" alt="BeeConnected" />
                        </a>
                    }
                </div>
                <div class="mid-footer">
                    <h6>@BeeKeepersBusiness.Resource.OfficialPartner</h6>
                    <a href="http://www.honeycouncil.ca/" target="_blank">
                        @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "fr")
                        {
                            <img src="~/images/CanadianHoneyCouncil-logo_FR.png" style="margin-left: 45px; height: 134px; margin-top: -19px;">
                        }
                        else
                        {
                            <img src="~/images/CanadianHoneyCouncil-logo_EN.png" style="margin-left: 45px; height: 134px; margin-top: -19px;">
                        }
                    </a>
                </div>
                <div class="right-footer">
                    <div class="full">
                        <h6>@BeeKeepersBusiness.Resource.ReachUs</h6>
                    </div>
                    <div class="full shade1">
                        <div class="full">
                            @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "fr")
                            {
                                <span>
                                350, rue Sparks, bur. 202 <br>
                                Ottawa, ON<br>
                                K1R 7S8<br>
                                Canada<br />
                                </span>
                            }
                            else
                            {
                                <span>
                                350 Sparks St. Suite 202 <br>
                                Ottawa, ON<br>
                                K1R 7S8<br>
                                Canada<br />
                                </span>
                            }
                            <img src="~/images/icon-phone.png" alt="" class="md-align" />
                            &nbsp;613-230-9881<br />
                            <img src="~/images/email-icon.png" alt="" class="md-align" style="height: 15px; width: 15px;" />
                            &nbsp;<a href="mailto:info@beeconnected.ca">info@beeconnected.ca</a>
                        </div>
                    </div>
                    <div class="full">
                    </div>
                </div>
            </div>
            <div class="lower-footer shade1">
                <div class="footer-lt">Copyright © @DateTime.Now.Year.ToString() Croplife Canada. @BeeKeepersBusiness.Resource.Allrightsreserved</div>
                <div class="footer-rt"><a href="@Url.Action("privacy", "page")" title="@BeeKeepersBusiness.Resource.PrivacyPolicy">@BeeKeepersBusiness.Resource.PrivacyPolicy</a> &nbsp;|&nbsp; <a href="@Url.Action("terms", "page")" title="@BeeKeepersBusiness.Resource.TermsConditions">@BeeKeepersBusiness.Resource.TermsConditions</a></div>
            </div>
        </div>
        <input type="hidden" id="menuid" />
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-75405003-2', 'auto');
ga('send', 'pageview');
</script>

</body>
</html>


<script type="text/javascript">
    $(document).ready(function () {
        $('.divscroll').niceScroll({});

        var str = window.location.href;

        $("#Home").removeAttr("style");
        $("#resource").removeAttr("style");
        $("#aboutus").removeAttr("style");
        $("#Contactus").removeAttr("style");
        $("#dashboard").removeAttr("style");

        if (str.indexOf("aboutus") >= 0) {
            $("#aboutus").addClass("active");
        }
        else if (str.indexOf("resource") >= 0) {
            $("#resource").addClass("active");

        }
        else if (str.indexOf("Contactus") >= 0) {
            $("#Contactus").addClass("active");
        }
        else if (str.indexOf("Dashboard") >= 0) {
            $("#dashboard").addClass("active");
        }
        else if (str == "http://beeconnected.ca" || str == "http://beeconnected.ca/home/" || str == "http://beeconnected.ca/home/index/") {
            $("#Home").addClass("active");
        }
    });

</script>

BeekeepersWeb/Views/Shared/defaultmap.cshtml
<img src='@System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString()/Images/img_map.png' style='height: 287px; width: 323px;'>