BeekeepersWeb/Controllers/UserMessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using BeeKeepersBusiness;
using BeeKeepersDataBase;
using BeeKeepersBusiness.utility;
using System.Threading;
using System.Net;
using System.IO;

namespace BeekeepersWeb.Controllers
{
    public class UserMessageController : ApplicationController
    {
        delegate void EmailDelegate(List<UserEmail> lstuseremail);
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult UserList()
        {
            if (UserSession.UserId != 0)
            {
                Messages msg = new Messages();
                //ViewBag.AdminCounter = MessageRepository.GetUnreadAdminCounter(UserSession.UserId);
                //var result = MessageRepository.getUsersListForInbox(UserSession.UserId);
                var result = msg.getUsersListForInbox(UserSession.UserId);
                return PartialView(result);
            }
            else
            {
                return Json(null);
            }
        }
        public ActionResult GetNewMessages(string LastMsgId, string otheruserid)
        {
            try
            {
                if (otheruserid == "0")
                {
                    ViewBag.touserid = otheruserid;
                    var result = MessageRepository.GetNewAdminMessages(Convert.ToInt64(LastMsgId), UserSession.UserId).OrderBy(s => s.addedon).ToList();
                    return Json(result);
                }
                else
                {
                    ViewBag.touserid = otheruserid;
                    var result = MessageRepository.GetNewMessages(Convert.ToInt64(LastMsgId), Convert.ToInt64(otheruserid), UserSession.UserId).OrderBy(s => s.addedon).ToList();
                    return Json(result);
                }

                
            }
            catch (Exception ex)
            {
                return Json("");
            }
        }
        public ActionResult Unreadcounter()
        {
            HttpWebRequest req = null;
            HttpWebResponse res = null;
            string url = "http://wds2.projectstatus.co.uk/democroplife/Services/service/BeeKeepersService.svc/UnreadMsgCounter";
            req = (HttpWebRequest)WebRequest.Create(url);
            req.Method = "POST";
            req.ContentType = "text/json;";
            req.Timeout = 10000000;
            StreamWriter writer = new StreamWriter(req.GetRequestStream());
            writer.WriteLine("{\"Lang\":\"en\",\"requestValue\":"+UserSession.UserId.ToString()+"}");
            writer.Close();

            res = (HttpWebResponse)req.GetResponse();
            string result;
            using (StreamReader rdr = new StreamReader(res.GetResponseStream()))
            {
                result = rdr.ReadToEnd();
            }
            return Json(result);
        }
        public ActionResult Show()
        {
            if (UserSession.UserId != 0)
            {
                return PartialView();
            }
            else
            {
                return Json(null);
            }
        }

        public ActionResult GetMessages(int id)
        {

            return View("Index");
        }
        //public string GetUnreadAdminCounter()
        //{
        //    return MessageRepository.GetUnreadAdminCounter(UserSession.UserId);
        //}
        public ActionResult PVUserMessage(Int64 id)
        {
            ViewBag.ServerDateTime = DateTime.Now.ToString();
            if (UserSession.UserId != 0)
            {
                if (id != 0)
                {
                    ViewBag.touserid = id;
                    var result = MessageRepository.GetMessages(UserSession.UserId, id).OrderBy(s => s.addedon).ToList();
                    return PartialView(result);
                }
                else
                {
                    ViewBag.touserid = 0;
                    var result = MessageRepository.GetAdminMessages(UserSession.UserId).OrderBy(s => s.addedon).ToList();
                    return PartialView("PVAdminMessage", result);
                }
            }
            else
            {
                return Json(null);
            }

        }
        [HttpPost]
        public ActionResult getmessages(Int64 id)
        {
            ViewBag.ServerDateTime = DateTime.Now.ToString();
            var result = MessageRepository.GetMessages(UserSession.UserId, id).OrderBy(s => s.addedon).ToList();
            return PartialView("PVUserMessage", result);
        }
        [HttpPost]
        public ActionResult SendMessage(FormCollection col)
        {
            ViewBag.ServerDateTime = DateTime.Now.ToString();
            List<sp_getMessages_Result> lstmesseges = new List<sp_getMessages_Result>(); 
            if (Convert.ToString(col["hdntouserid"]) != null && Convert.ToString(col["hdntouserid"]) != "")
            {
                Int64 touserid = Convert.ToInt64(col["hdntouserid"]);
                ViewBag.touserid = Convert.ToString(touserid);
                using (Messages messages = new Messages())
                {
                    Int64? result = messages.SendMessage(UserSession.UserId, Convert.ToInt64(col["hdntouserid"]), col["txtMessage"].ToString(), "",1);
                    if (result != null && result > 0)
                    {

                        var installation = Data.Entities.tblinstallations.Where(s => s.userid == touserid).ToList();
                        var fromuserinfo = Data.Entities.tblusers.Where(s => s.id == UserSession.UserId).FirstOrDefault();
                        var touserinfo = Data.Entities.tblusers.Where(s => s.id == touserid).FirstOrDefault();

                        string langEmail = new Common().GetLanguage4Emails(touserid);
                        List<UserEmail> lstuseremail = new List<UserEmail>();
                        UserEmail objuseremail = new UserEmail();
                        objuseremail.fromUserName = fromuserinfo.username;
                        objuseremail.toUserName = touserinfo.username;
                        objuseremail.toEmailId = touserinfo.email;
                        objuseremail.UserLanguage = langEmail;
                        objuseremail.message = fromuserinfo.username + " " + new SiteLanguages().GetResxNameByValue(langEmail, "sentyouamessage");
                        lstuseremail.Add(objuseremail);

                        int? badgecount = new Common().GetNotificationCounter(touserid);
                        if (installation != null)
                        {
                            foreach (var item in installation)
                            {
                                string langnoti = new Common().GetLanguage4Notification(item.userid);
                                if (item.devicetype == "1")
                                {
                                    iPhonePush.SendNotice(item.devicetoken, fromuserinfo.username + " " + new SiteLanguages().GetResxNameByValue(langnoti, "sentyouamessage"), badgecount, "Message", UserSession.UserId, result, "");
                                }
                                else if (item.devicetype == "2")
                                {
                                    AndroidPushNotice.SendNotice(item.devicetoken, fromuserinfo.username + " " + new SiteLanguages().GetResxNameByValue(langnoti, "sentyouamessage"), badgecount, "Message", UserSession.UserId, result, "");
                                }
                            }
                            EmailDelegate emailDelegate = new EmailDelegate(UserEmail.SendNotificationMails4Message);
                            AsyncCallback cb = new AsyncCallback(MyAsyncCallback);
                            IAsyncResult ar = emailDelegate.BeginInvoke(lstuseremail, cb, emailDelegate);

                        }

                        ViewBag.message = Resource.Messagesent;
                        ViewBag.status = "1";
                    }
                    else
                    {
                        ViewBag.message = Resource.MessagenotsentTryagain;
                        ViewBag.status = "0";
                        ModelState.AddModelError("", "");
                    }
                }
                lstmesseges = MessageRepository.GetMessages(UserSession.UserId, Convert.ToInt64(col["hdntouserid"])).OrderBy(s => s.addedon).ToList();
            }
            else
            {
                ViewBag.message = Resource.Pleaseselectuser;
                ViewBag.status = "0";
                lstmesseges = new List<sp_getMessages_Result>(); 
            }
            return PartialView("PVUserMessage", lstmesseges);
        }

        public JsonResult CountUnreadMsg()
        {
            List<MsgCounter> lstmsgCounter = (from a in MessageRepository.GetUnreadMSGCounter(UserSession.UserId).AsEnumerable() select new MsgCounter { UnreadCounter=a.unreadcount,UserId=0}).ToList();
            return Json(null);
        }
        public static void MyAsyncCallback(IAsyncResult ar)
        {

        }

    }
}

BeekeepersWeb/Views/UserMessage/Index.cshtml
@model BeekeepersWeb.Models.ClassSendMessage
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#messages").addClass("leftmenuactive");
    });
    var ButtonKeys = { "EnterKey": 13 };
    $(function () {
        $("#MainForm").keypress(function (e) {
            if (e.which == ButtonKeys.EnterKey) {
                var defaultButtonId = $(this).attr("defaultbutton");
                $("#" + defaultButtonId).click();
                return false;
            }
        });
    });
</script>
<style type="text/css">
   
    .text_message {
        float: left;
        border: 1px solid;
        padding: 5px;
        width: 420px;
    }

    .message_main {
        float: left;
        height: 500px;
        margin: 10px;
        width: 700px;
    }

    .users_sub a {
        text-decoration: none;
        color: #18723d;
    }

   
    .users_main a:active {
        color: red !important;
        background: #f4f2d1;
    }

    .users_main {
        float: left;
        height: 480px;
        margin: 10px;
        border: 1px solid;
        width: 238px;
    }

    .users_main1 {
        float: left;
        height: 440px;
        overflow-y: scroll;
        width: 238px;
        background:#DDE6C3;
    }

    .users_sub {
        background: #9FBC4A;
        border-bottom:1px #00713D dotted; 
        color: #000;
        float: left;
        height: auto;
        padding: 7px;
        width: 222px;
        cursor: pointer;
    }
    
    .users_sub1 {
        background: none repeat scroll 0 0 #dde6c3;
        border: 1px solid #fff;
        color: #000;
        float: left;
        height: auto;
        padding: 7px;
        width: 204px;
    }


    .message_leftmain {
        float: right;
        height: 375px;
        width: 446px;
        overflow-y: auto;
    }

    .message-txt {
        float: left;
        margin: 7px;
        width: 432px;
        height: 88px;
    }

    .message1 {
        background: #9FBC4A;
        float: left;
        height: auto;
        margin: 5px;
        overflow-y: auto;
        padding: 5px;
        width: 406px;
    }

    .message2 {
        background: none repeat scroll 0 0 #c7d5db;
        float: left;
        height: auto;
        margin: 5px;
        overflow-y: auto;
        padding: 10px;
        width: 485px;
    }
    .message1_unread {
        background: none repeat scroll 0 0 #00af5c;
        float: left;
        height: auto;
        margin: 5px;
        overflow-y: auto;
        padding: 5px;
        width: 423px;
    }
    
    .alert-danger {
        background-color: #f2dede;
        border-color: #ebccd1;
        color: #a94442;
        float: left;
        margin-left: 20px;
        margin-top: 320px;
        padding: 10px;
        position: absolute;
        text-align: center;
        width: 461px;
    }

    .panel-danger {
        margin-left: 50px !important;
        margin-top: -90px !important;
    }
    .SelectedUser {
        background:#fff !important;
    }
</style>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@Html.Partial("loginmenus")
<div class="right-db">
    <div class="full">
        <h1>
            @BeeKeepersBusiness.Resource.MyMessages
        </h1>
    </div>
    <div class="clear"></div>
    <div class="full">
        <div class="users_main">
            <div class="users_sub1" style="text-align: center; width: 222px; border-bottom: 2px solid;">
                 @BeeKeepersBusiness.Resource.UsersList
                <a href="@Url.Action("index","UserMessage")"><img src="~/Images/refresh_icon.png" title="Refresh Messages" style="float:right;cursor:pointer" /></a>
            </div>
            <div class="users_main1 divscroll">
                @Html.Action("UserList", "UserMessage")
            </div>
        </div>
        <div class="message_left">
            @*@using (Html.BeginForm("SendMessage", "UserMessage"))*@


            @using (Ajax.BeginForm("SendMessage", "UserMessage", new AjaxOptions { UpdateTargetId = "partialSummaryDiv" }, new { defaultbutton = "SubmitButton", id = "MainForm" }))
            {
                <div class="message_leftmain" id="partialSummaryDiv" style="float:left;">
                </div>
                <div class="message-txt" id="div_message-txt">
                    @Html.Partial("ValidationSummary", ViewData.ModelState)
                    @Html.TextAreaFor(Model => Model.txtMessage, 3, 60, new { @class = "text_message", @placeholder = @BeeKeepersBusiness.Resource.Typeyourmessagehere })

                    @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "hi")
                    {
                        <input type="image" src="~/Images/send_BTN_hi.png" style="float: right; height: 38px;" id="SubmitButton" />
                    }
                    else if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value == "mr")
                    {
                        <input type="image" src="~/Images/send_BTN_mr.png" style="float: right; height: 38px;" id="SubmitButton" />
                    }
                    else
                    {
                        <input type="image" src="~/Images/send_BTN_en.png" style="float: right; height: 38px;" id="SubmitButton" />
                    }

                </div>
            }
        </div>
    </div>

</div>

@section Scripts {
    @Styles.Render("~/Content/themes/base/css")

    <script type="text/javascript">
        $('.users_sub').click(function () {
            var id = this.id;
            $('#' + id).removeAttr("style");
            var userid = id.split('_')[1];
            $('#partialSummaryDiv').html('<div style="margin: 100px auto; width: 150px; white-space: nowrap; height: 112px;text-align: center; z-index: 1000;"><table border="0" style="text-align: center;"><tr><td align="left"><img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString()/Images/loading.gif" /></td></tr></table></div>');
            $.ajax({
                url: '@Url.Action("PVUserMessage", "UserMessage")',
                data: { id: userid },
                cache: false,
                type: "POST",
                success: function (data) {
                    if (data == null) {
                        window.parent.location = "userlogin/login"
                    }
                    else {
                        $('#partialSummaryDiv').html(data);
                    }
                },
                error: function (reponse) {
                    alert("error : " + JSON.stringify("@Html.Raw(@BeeKeepersBusiness.Resource.ThereisaproblemPleasetryagainlater)"));
                }
            });

        });
    </script>
}

BeekeepersWeb/Views/UserMessage/PVAdminMessage.cshtml
@model IEnumerable<BeeKeepersDataBase.sp_GetAdminMessages_Result>
<style type="text/css">
    .maintimego {
        font-size: 12px; color: rgb(97, 73, 47); float: left; margin-left: 10px; margin-top: 2px;
    }
</style>
<script src="~/Scripts/jquery.timeago.js" type="text/javascript"></script>
<script src="~/Scripts/test_helpers.js" type="text/javascript"></script>

   
<script type="text/javascript">
    $('.users_sub').each(function () {
        $(this).removeClass("SelectedUser");
    });
    $("#admin_0").attr("class", "users_sub SelectedUser");

    jQuery(document).ready(function ($) {
        prepareDynamicDates();
        $("label.timeago").timeago();
        document.getElementById("div_message-txt").style.display = "none";
        document.getElementById("partialSummaryDiv").style.height = "491px";
    });
</script>
<div style="float:left;height:488px !important;overflow-y:auto;" id="div_messages" class="divscroll">
    <input type="hidden" id="hdnServerDateTime" value="@ViewBag.ServerDateTime -0400" />
@foreach (var item in Model)
{
    if (item.status == 1)
    {
        <div class="message1"  style="background:#DDE6C3">
            <div style="float:left;width:100%">
                <div  class="maintimego"><label class="timeago" title="@item.addedon.ToString("MM/dd/yyyy hh:mm:ss tt zzz", new System.Globalization.CultureInfo("en-US"))" /></div>
            </div>
            <div style="float:left;">@item.message</div>
        </div>
    }
    else
    {
         <div class="message1">
            <div style="float:left;width:100%">
                <div  class="maintimego"><label class="timeago" title="@item.addedon.ToString("MM/dd/yyyy hh:mm:ss tt zzz", new System.Globalization.CultureInfo("en-US"))" /></div>
            </div>
            <div style="float:left;">@item.message</div>
        </div>
    }
    
    
}
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var objDiv = document.getElementById("div_messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    });
</script>

BeekeepersWeb/Views/UserMessage/PVUserMessage.cshtml
@model IEnumerable<BeeKeepersDataBase.sp_getMessages_Result>
<style type="text/css">
    .maintimego {
        font-size: 12px; color: rgb(97, 73, 47); float: left; margin-left: 10px; margin-top: 2px;
    }
</style>
<script src="~/Scripts/jquery.timeago.js" type="text/javascript"></script>
<script src="~/Scripts/test_helpers.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        prepareDynamicDates();
        $("label.timeago").timeago();
        document.getElementById("div_message-txt").style.display = "block";
        document.getElementById("partialSummaryDiv").style.height = "375px";
    });
</script>
@if (Model.FirstOrDefault() != null)
{
    <script type="text/javascript">
        $('.users_sub').each(function () {
            $(this).removeClass("SelectedUser");
        });
        $("#user_"+@ViewBag.touserid.ToString()).attr("class","users_sub SelectedUser");
    </script> 
}
<input type="hidden" id="hdntouserid" name="hdntouserid" value="@ViewBag.touserid" />
<div id="message">
    @if (@ViewBag.status != null && @ViewBag.status == "1")
    {
        <div class="alert alert-success" role="alert">@ViewBag.message</div> 
        <script type="text/javascript">
            $("#pageloaddiv").fadeOut(1000);
            $("#txtMessage").val("");
            window.setTimeout(function () { $('#message').fadeOut(1000); }, 2000);
        </script>
    }
    else if (@ViewBag.status != null && @ViewBag.status == "0")
    { 
        <div class="alert alert-danger" role="alert">@ViewBag.message</div>   
        <script type="text/javascript">
            $("#pageloaddiv").fadeOut(1000);
            window.setTimeout(function () { $('#message').fadeOut(1000); }, 2000);
        </script>
    }
</div>

<div style="float:left;height:375px !important;overflow-y:auto;" id="div_messages" class="divscroll">
<input type="hidden" id="hdnServerDateTime" value="@ViewBag.ServerDateTime -0400" />
@foreach (var item in Model)
{
    //string classname = "";
    //if (@item.status.ToString() == "1" && @item.touserid == @BeekeepersWeb.UserSession.UserId)
    //{
    //    classname = "message1_unread"; @classname
    //}
    string image = "";
      if (item.usertype == 1)
      {
          image = System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString() + "/Images/bee.png";
      }
      else if (item.usertype == 2)
      {
          image = System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString() + "/Images/farmer.png";
      }
      else
      {
          image = System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString() + "/Images/tractor.png";
      }
      if (item.status == 1 & BeekeepersWeb.UserSession.UserId != item.fromuserid)
      {
        <div class="message1" style="background:#DDE6C3">
            <div style="float:left;width:100%">
                <div style="float:left;"><img src="@image" /></div>
                <div  class="maintimego"><label class="timeago" title="@item.addedon.ToString("MM/dd/yyyy hh:mm:ss tt zzz", new System.Globalization.CultureInfo("en-US"))" /></div><br />
            </div>
            <div style="float:left;">@item.body</div>
        </div>
      }
      else 
      {
          <div class="message1">
            <div style="float:left;width:100%">
                <div style="float:left;"><img src="@image" /></div>
                <div  class="maintimego"><label class="timeago" title="@item.addedon.ToString("MM/dd/yyyy hh:mm:ss tt zzz", new System.Globalization.CultureInfo("en-US"))" /></div><br />
            </div>
            <div style="float:left;">@item.body</div>
        </div>
      }
    
}
 </div>
<script type="text/javascript">
    $(document).ready(function () {
        var objDiv = document.getElementById("div_messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    });
</script>

BeekeepersWeb/Views/UserMessage/UserList.cshtml
@model IEnumerable<BeeKeepersBusiness.GetInboxUserResponse>
@foreach (var item in Model)
{
    if (item.userId == 0)
    {
        if (item.status == 1)
        {
            <div class="users_sub" id="admin_0" style="background:#DDE6C3;">
                @*@Ajax.ActionLink(@item.username, "PVUserMessage", "UserMessage", new { id = item.userid }, new AjaxOptions { UpdateTargetId = "partialSummaryDiv" }, new { @id="user_"+item.userid.ToString(),@class="userlist"})*@
                <div class="userlist">
                    <div style="float: left;">@BeeKeepersBusiness.Resource.Admin</div>
                    @* <div class="unread_counter" id="divCounter_0">
                           @ViewBag.AdminCounter.ToString()
                       </div>*@
                </div>
            </div>
        }
        else
        {
            <div class="users_sub" id="admin_0">
                @*@Ajax.ActionLink(@item.username, "PVUserMessage", "UserMessage", new { id = item.userid }, new AjaxOptions { UpdateTargetId = "partialSummaryDiv" }, new { @id="user_"+item.userid.ToString(),@class="userlist"})*@
                <div class="userlist">
                    <div style="float: left;">@BeeKeepersBusiness.Resource.Admin</div>
                    @* <div class="unread_counter" id="divCounter_0">
                           @ViewBag.AdminCounter.ToString()
                       </div>*@
                </div>
            </div> 
        }
    }
    else
    {
        if (item.status == 1)
        {
            <div class="users_sub" id="user_@item.userId.ToString()" style="background:#DDE6C3;">
                <div class="userlist">
                    <div style="float: left;">@item.userName</div>
                </div>
            </div>
        }
        else
        {
            <div class="users_sub" id="user_@item.userId.ToString()">
                <div class="userlist">
                    <div style="float: left;">@item.userName</div>
                </div>
            </div>
        }
    }
    
    
@*@Ajax.ActionLink(@item.username, "PVUserMessage", "UserMessage", new { id = item.userid }, new AjaxOptions { UpdateTargetId = "partialSummaryDiv" }, new { @id="user_"+item.userid.ToString(),@class="userlist"})*@
@*<div class="unread_counter"  id="divCounter_@item.userid">@item.unreadcount.ToString()</div>*@
    
}