BeekeepersWeb/Controllers/UserActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BeekeepersWeb.Models;
using BeeKeepersBusiness;
using PagedList;
using BeeKeepersDataBase;
using System.Globalization;
namespace BeekeepersWeb.Controllers
{
    public class UserActivityController : ApplicationController
    {
        //
        // GET: /UserActivity/

        public ActionResult Index(int? page)
        {
            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"];
                ViewBag.status = TempData["status"];
            }
            Activities activities = new Activities();
            var result = activities.GetUserActivityList(UserSession.UserId).OrderByDescending(s => s.startdate).ToList();
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(result.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ActivityModel Model)
        {
            try
            {
                Activities activities = new Activities();
                string startDate = DateTime.ParseExact(Model.startdate, "dd-MM-yyyy", null).ToString("dd/MMM/yyyy",new System.Globalization.CultureInfo("en-US"));
                string endDate = DateTime.ParseExact(Model.enddate, "dd-MM-yyyy", null).ToString("dd/MMM/yyyy", new System.Globalization.CultureInfo("en-US"));
                Int64? result = activities.AddActivity(UserSession.UserId, Convert.ToInt32(UserSession.UserRole), Model.note, Model.latitude, Model.longitude, startDate, endDate);
                if (result != null && result > 0)
                {
                    try
                    {
                        new Activities().SendNotificationToUsers(result,UserSession.UserId, Convert.ToInt32(UserSession.UserRole), Model.latitude, Model.longitude, startDate, endDate, Model.note);
                    }
                    catch (Exception ex)
                    {
                        using (errorlogBusiness errorlog = new errorlogBusiness())
                        {
                            errorlog.InsertErrorLog(0, "notification", ex.Message, "");
                        }
                    }
                    ModelState.Clear();
                    TempData["message"] = BeeKeepersBusiness.Resource.Activityaddedsuccessfully;
                    TempData["status"] = "1";
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("", Resource.ActivitynotaddedTryagain);

                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", Resource.ActivitynotaddedTryagain);
                return View();
            }
        }

        //
        // GET: /UserActivity/Edit/5

        public ActionResult Edit(Int64 id)
        {
            try
            {
                if (TempData["message"] != null)
                {
                    ViewBag.message = TempData["message"];
                    ViewBag.status = TempData["status"];
                }

                Activities activities = new Activities();
                ActivityResponse activityresponse = activities.EditActivity4Web2(id);
                if (activityresponse != null)
                {
                    ActivityModel Model = new ActivityModel();
                    Model.enddate = activityresponse.endDate;
                    Model.startdate = activityresponse.startDate;
                    Model.usertype = Convert.ToInt32(activityresponse.userType);
                    Model.note = activityresponse.note;
                    Model.latitude = activityresponse.latitude;
                    Model.longitude = activityresponse.longitude;
                    return View(Model);
                }
                else
                {
                    TempData["message"] = Resource.Activitydetailsnotget;
                    TempData["status"] = "0";
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {
                TempData["message"] = Resource.Activitydetailsnotget;
                TempData["status"] = "0";
                return RedirectToAction("index");
            }

        }

        //
        // POST: /UserActivity/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, ActivityModel model)
        {
            try
            {
                Activities activities = new Activities();
                string startDate = DateTime.ParseExact(model.startdate, "dd-MM-yyyy", null).ToString("dd/MMM/yyyy",new System.Globalization.CultureInfo("en-US"));
                string endDate = DateTime.ParseExact(model.enddate, "dd-MM-yyyy", null).ToString("dd/MMM/yyyy",new System.Globalization.CultureInfo("en-US"));
                Int64? result = activities.UpdateActivity(UserSession.UserId, model.latitude, model.longitude, Convert.ToInt32(UserSession.UserRole), startDate, endDate, id, model.note);
                if (result != null && result > 0)
                {
                    TempData["message"] = Resource.Activityupdatedsuccessfully;
                    TempData["status"] = "1";
                    return RedirectToAction("index");
                }
                else
                {
                    TempData["message"] = Resource.ActivitynotupdatedTryagain;
                    TempData["status"] = "0";
                }
                return RedirectToAction("Edit", id);
            }
            catch
            {
                TempData["message"] = Resource.ActivitynotupdatedTryagain;
                TempData["status"] = "0";
                return RedirectToAction("Edit", id);
            }
        }
        public ActionResult Cancel()
        {
            return RedirectToAction("index");
        }
        public ActionResult Delete(int id)
        {
            Activities activity = new Activities();
            Int64? result = activity.DeleteActivity(id);
            if (result != null && result == 1)
            {
                TempData["message"] = Resource.Activitydeletedsuccessfully;
                TempData["status"] = "1";

            }
            else
            {
                TempData["message"] = Resource.ActivitynotdeletedTryagain;
                TempData["status"] = "0";
            }
            return RedirectToAction("index");
        }

        public ActionResult ViewAround(Int64 id)
        {

            if (TempData["message"] != null)
            {
                ViewBag.message = TempData["message"];
                ViewBag.status = TempData["status"];
            }
            if (TempData["txtmessage"] != null)
            {
                ViewBag.txtmessage = TempData["txtmessage"];
            }

            ActivityResponse objactivity = new Activities().EditActivity4Web(id);
            ViewBag.userid = objactivity.userId;
            ViewBag.note = objactivity.note;
            ViewBag.acitvityid = objactivity.id;
            ViewBag.latitude = objactivity.latitude;
            ViewBag.longitude = objactivity.longitude;
            ViewBag.startdate = string.Format("{0:dd-MMM-yyyy}", objactivity.startDate);
            ViewBag.enddate = string.Format("{0:dd-MMM-yyyy}", objactivity.endDate); 
            Activities activities = new Activities();
            ViewBag.activityArround = activities.ActivityList4Web(UserSession.UserId, Convert.ToInt64(UserSession.UserRole), objactivity.latitude, objactivity.longitude, objactivity.startDate, objactivity.endDate, 5);
            return View();


        }
        public ActionResult SendBroadcast(FormCollection col)
        {
            Messages messages = new Messages();
            int result = messages.SendBroadcastMessage4web(Convert.ToInt64(col["hdnactivity"]), col["txtmessage"].ToString());
            if (result >= 1)
            {
                TempData["message"] = Resource.Messagesentto+" " + result.ToString() + " "+Resource.users;
                TempData["status"] = "1";
            }
            else if (result == -2)
            {
                TempData["txtmessage"] = col["txtmessage"].ToString();
                TempData["message"] = Resource.Usersnotavailabletosendmessage;
                TempData["status"] = "0";
            }
            else
            {
                TempData["txtmessage"] = col["txtmessage"].ToString();
                TempData["message"] = Resource.Messagenotsent;
                TempData["status"] = "0";
            }
            return RedirectToAction("ViewAround", new { @id = Convert.ToInt64(col["hdnactivity"]) });
        }
    }
}

BeekeepersWeb/Views/UserActivity/Index.cshtml
@model PagedList.IPagedList<BeeKeepersDataBase.SP_Select_Activitylist_Result>
@using PagedList.Mvc;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    
    $(document).ready(function () {
        $("#myactivities").addClass("leftmenuactive");
    });
</script>

<style type="text/css">
    .alert-success {
        background-color: #b2dba1;
        border-color: #d6e9c6;
        color: #468847;
        margin-left: 285px;
        margin-top: 0px;
        padding: 15px;
        position: absolute;
        text-align: center;
        width: auto;
    }

    .myactivitylist {
        float: right;
        width: 700px;
        margin: 10px;
        margin-left: 50px;
    }

    .myactivitylist_node {
        float: left;
        width: 680px;
        margin: 5px;
        background: #E7D6A5;
    }

    .myactivitylist_img {
        float: left;
        width: 110px;
        height: 110px;
        margin: 5px;
    }

    .myactivitylist_detail {
        float: left;
        width: 545px;
        height: auto;
        margin: 5px;
    }

    .myactivitylist_label {
        float: left;
        width: 530px;
        height: auto;
        margin: 5px;
    }

    
    .myactivitylist_labelsub  {
        background: none repeat scroll 0 0 #fff;
    float: left;
    height: 20px;
    margin: 2px 20px 2px 2px;
    padding: 7px;
    width: auto;
    color:#55703C;
    border-radius:5px;
    border:1px solid;
    }
    .myactivitylist_labelsub a {
       text-decoration:none; 
    color:#55703C;
    }
    .myactivitylist_labelsub a:hover {
       text-decoration:none; 
       color:#000
    }
    .myactivitylist_labelsub:hover {
        background: none repeat scroll 0 0 #7EB69C;
    float: left;
    height: 20px;
    margin: 2px 20px 2px 2px;
    padding: 7px;
    width: auto;
    border-radius:5px;
    border:1px solid;
    }
</style>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@Html.Partial("loginmenus")
<div class="right-db">
    <div class="full">
    <h1 >@BeeKeepersBusiness.Resource.MyActivities
          <span style="float: right; font-size: 18px; font-family: arial; font-style: normal;">
              <a href="@Url.Action("Create", "UserActivity")" style="text-decoration:none;color:#0B4B00;">
                  <img src="~/Images/addactivitygreen.png" />
                  &nbsp;@BeeKeepersBusiness.Resource.AddNewActivity</a>
          </span>
    </h1>
 </div>
    <div id="message">
        @if (@ViewBag.status != null && @ViewBag.status == "1")
        {
            <div class="alert alert-success" role="alert">@ViewBag.message</div> 
            <script type="text/javascript">
                window.setTimeout(function () { HideMessage(); }, 2000);
            </script>
        }
        else if (@ViewBag.status != null && @ViewBag.status == "0")
        { 
            <div class="alert alert-danger" role="alert">@ViewBag.message</div>   
            <script type="text/javascript">
                window.setTimeout(function () { HideMessage(); }, 2000);
            </script>
        }
    </div>
    <div class="clear"></div>
    <div class="myactivitylist">
        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
            <div class="myactivitylist_node">
                <div class="myactivitylist_img">
                    @if (BeekeepersWeb.UserSession.UserRole == "1")
                    {
                        <img src="~/Images/beekeeper_big@2x.png" />
                    }
                    else if (BeekeepersWeb.UserSession.UserRole == "2")
                    {
                        <img src="~/Images/farmer_big@2x.png" />
                    }
                    else
                    {
                        <img src="~/Images/contractor_big@2x.png" />
                    }


                    
                </div>
                <div class="myactivitylist_detail">
                    <div class="myactivitylist_label">
                       @{
                            BeeKeepersBusiness.SiteLanguages sitelang = new BeeKeepersBusiness.SiteLanguages();
                            string strusertype = sitelang.GetResxNameByValue(Request.Cookies.Get("culture").Value, @item.usertypetxt);                         
                        }
                        @strusertype
                    </div>
                    <div class="myactivitylist_label">
                        <img src="~/Images/calendar_icon@2X.png" />&nbsp;@item.startdate.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US")) &nbsp;&nbsp;&nbsp;&nbsp;
                        <img src="~/Images/calendar_icon@2X.png" />&nbsp;@item.enddate.ToString("dd-MMM-yyyy", new System.Globalization.CultureInfo("en-US"))
                    </div>
                    <div class="myactivitylist_label">
                        @item.note
                    </div>
                    <div class="myactivitylist_label">
                        <div class="myactivitylist_labelsub">
                            <a href="@Url.Action("ViewAround", "UserActivity", new { @id = @item.id })" style="text-decoration:none;color:#000;">
                                <div style="float:left;"><img src="~/Images/arround_activity.png" /></div>
                                @BeeKeepersBusiness.Resource.Viewnearbyactivities</a>
                        </div>
                        <div class="myactivitylist_labelsub">
                            <a href="@Url.Action("Edit", "UserActivity", new { @id = @item.id })" style="text-decoration:none;color:#000;">
                                <div style="float:left;"><img src="~/Images/editgreen_icon.png" /></div>
                                @BeeKeepersBusiness.Resource.Edit</a>
                        </div>
                        <div class="myactivitylist_labelsub">
                            <a href="@Url.Action("Delete", "UserActivity", new { @id = @item.id })" onclick= "return confirm('@BeeKeepersBusiness.Resource.ConfirmDeleteActivity')"   style="text-decoration:none;color:#000;">
                                <div style="float:left;"><img src="~/Images/delete_icon.png" /></div>
                                @BeeKeepersBusiness.Resource.Delete</a>
                        </div>
                    </div>
                </div>
            </div>
                    
            }
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))    
        }
        else
        {
            <div style="float: left; width: 100%; text-align: center;">@BeeKeepersBusiness.Resource.NoActivitiesaddedyet</div>
        }

    </div>

</div>

BeekeepersWeb/Views/UserActivity/ViewAround.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
   

    .input-block {
        width: 96%;
        margin: 10px;
    }

    .alert-danger {
        background-color: #f2dede;
    border-color: #ebccd1;
    color: #a94442;
    float: left;
    margin-left: 293px;
    margin-top: 135px;
    padding: 10px;
    position: absolute;
    text-align: center;
    width: 633px;
    z-index: 15000;
    }

    .alert-success {
       background-color: #dff0d8;
        border-color: #d6e9c6;
        color: #468847;
        margin-left: 275px;
        margin-top: 95px;
        padding: 8px;
        position: absolute;
        text-align: center;
        width: 675px;
        z-index: 1000;
    }

    #map-canvas {
        border: 1px solid #777777;
        border-radius: 5px;
        height: 470px;
        width: 691px;
    }
</style>
@Html.Partial("loginmenus")
<div class="right-db">
 <div class="full">
    <h1> @BeeKeepersBusiness.Resource.Viewnearbyactivities</h1>
        </div>
    
    <div class="full" >
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
        <script src="https://code.jquery.com/ui/1.10.2/jquery-ui.min.js" integrity="sha256-FgiaQnQazF/QCrF9qSvpRY6PACn9ZF8VnlgqfqD1LsE=" crossorigin="anonymous"></script>

       <script src="https://maps.googleapis.com/maps/api/js?v=3&key=AIzaSyAPAJCWKEzIL_kM-EBU9e-u0kMDffzoVwE&libraries=places"></script>
        
        <script type="text/javascript">
            
            function ShowBroadcast()
            {
                $("#div_broadcast").slideDown(500);
            }
            function HideBroadcast()
            {
                document.getElementById("txtmessage").value="";
                $("#div_broadcast").slideUp(500);
            }
            function messagevalidation()
            {
                if(document.getElementById("txtmessage").value=="")
                {
                    alert("@BeeKeepersBusiness.Resource.Pleaseenterbroadcastmessage");
                    return false;
                }
                else
                {
                    return true;
                }
            }
            function initialize() {
                var center = new google.maps.LatLng(@ViewBag.latitude, @ViewBag.longitude);
                var marker;
                var txtLat;
                var txtlong;
                var bool = true;
                txtLat = @ViewBag.latitude;
                txtlong = @ViewBag.longitude;
                bool = false;

                var myLatlng = new google.maps.LatLng(txtLat, txtlong);
        @if (BeekeepersWeb.UserSession.UserRole == "1")
        {
            @:image_me = "http://beeconnected.ca/images/pin_beekeeper.png";
        }
        else
        {
            @:image_me = "http://beeconnected.ca/images/pin_contractor.png";
        }
        
        
                var mapOptions = {
                    zoom: bool ? 8 : 10,
                    center: myLatlng,
                    MapTypeId: google.maps.MapTypeId.TERRAIN

                };
                var map = new google.maps.Map(document.getElementById('map-canvas'),
                  mapOptions);
                var circle = new google.maps.Circle({
                    center: center,
                    map: map,
                    radius: 5000,          // IN METERS.
                    fillColor: '#FF6600',
                    fillOpacity: 0.3,
                    strokeColor: "#FFF",
                    strokeWeight: 0         // DON'T SHOW CIRCLE BORDER.
                });
                var bounds = new google.maps.LatLngBounds();
                var infowindow = new google.maps.InfoWindow();
                var latlng = new google.maps.LatLng(@ViewBag.latitude, @ViewBag.longitude);
                bounds.extend(latlng);
                marker=new google.maps.Marker({map: map,icon: image_me,position: new google.maps.LatLng(@ViewBag.latitude, @ViewBag.longitude)});
                @if (@ViewBag.activityArround != null)
                {
                    foreach (var item in @ViewBag.activityArround)
                    {
                        if (item.usertype == 1)
                        {
                            @:image = "http://beeconnected.ca/images/pin_beekeeper.png";
                        }
                                    else
                                    {
                            @:image = "http://beeconnected.ca/images/pin_contractor.png";
                        }
                            @:var latlng = new google.maps.LatLng(@item.latitude, @item.longitude);
                                            @:bounds.extend(latlng);
                                            @:var marker = new google.maps.Marker({clickable: true,map: map,icon: image,position: new google.maps.LatLng(@item.latitude, @item.longitude)});
                                            @:google.maps.event.addListener(marker, 'click', function() {infowindow.setContent('<div style="float:left;width:200px;"><div style="float:left;width:200px;">@item.username</div><div style="float:left;width:200px;"><a href="@Url.Action("index", "userprofile", new { @id = @item.userid,@actid=@item.id})">@item.note</a></div></div>');infowindow.open(map, this);});
                        }
                     }
            }
        
            google.maps.event.addDomListener(window, 'load', initialize);
    
        </script>
       
        <div style="float: left; width: 100%;">
            <div style="float: left; padding: 0 10px 10px; width: 95%;">
                <div style="float: left; width: 85%;">
                    <img src="~/Images/calendar_icon@2X.png" style="margin-right: 10px; float: left;" /><div style="float: left;">@BeeKeepersBusiness.Resource.Startdate : @ViewBag.startdate </div>
                    &nbsp;&nbsp;
                    <img src="~/Images/calendar_icon@2X.png" style="margin-right: 10px; float: left; margin-left: 30px;" /><div style="float: left;">@BeeKeepersBusiness.Resource.Enddate : @ViewBag.enddate</div>
                </div>
                <div style="float: right; width: 6%;">
                    <img src="~/Images/emailicon@2x.png" style="cursor: pointer;" title="@BeeKeepersBusiness.Resource.SendBroadcastMessage" onclick="ShowBroadcast();" />

                </div>
            </div>
            <div style="float: left; width: 100%;">
                <div style=" background: none repeat scroll 0 0 rgb(255, 255, 255);border: 2px solid #0b4b00;float: left;height: 105px;position: absolute;top: auto;width: 688px;z-index: 10000; display: none;" id="div_broadcast">
                    @using (Html.BeginForm("SendBroadcast", "UserActivity"))
                    {
                        <input type="hidden" name="hdnactivity" id="hdnactivity" value="@ViewBag.acitvityid" />   
                        @Html.TextArea("txtmessage", new { @class = "broadcasttextarea", @placeholder = @BeeKeepersBusiness.Resource.Message })
                        <div class="input_block">
                            
                            <div style="float: right; width: 84px;">
                                @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value=="fr")
                                {
                                    <img   style="height:28px;cursor:pointer;" src="~/Images/cancelbtn1.png" onclick="HideBroadcast();" />
                                }
                                else
                                {
                                    <img   style="height:28px;cursor:pointer;" src="~/Images/cancelbtn1_en.png" onclick="HideBroadcast();" />
                                }
                            </div>
                            <div style="float: right; width: 71px;">
                                @if (Request.Cookies.Get("culture") != null && Request.Cookies.Get("culture").Value=="fr")
                                {
                                    <input type="image" src="~/Images/send_BTN.png" style="width: 65px; height: 28px; float: left" onclick="return messagevalidation();" />
                                }
                                else
                                {
                                    <input type="image" src="~/Images/send_BTN_en.png" style="width: 65px; height: 28px; float: left" onclick="return messagevalidation();" />
                                }

                            </div>
                        </div>
                    }

                </div>
                <div id="map-canvas"></div>
            </div>
        </div>
    </div>

</div>
<div id="message">
    @if (@ViewBag.status != null && @ViewBag.status == "1")
    {
            
        <div class="alert alert-success" role="alert">@ViewBag.message</div> 
        <script type="text/javascript">
            $(document).ready(function() {
                document.getElementById("txtmessage").value="";
            });
            window.setTimeout(function () { HideMessage(); }, 2000);
        </script>
    }
    else if (@ViewBag.status != null && @ViewBag.status == "0")
    { 
        <div class="alert alert-danger" role="alert">@ViewBag.message</div>   
        <script type="text/javascript">
            $(document).ready(function() {
                   
                $("#div_broadcast").slideDown(500);
            });
            window.setTimeout(function () { HideMessage(); }, 2000);
        </script>
    }
</div>
 